#!/bin/sh

# Passenger way
# touch /home/duwebadmin/duwc.newfoo_site1.com/current/tmp/restart.txt

# Mongreal way

/var/rails/duwc/current/script/process/spawner mongrel --environment=production --instances=1 --address=204.42.157.43 --port=3000